name: Publish

on:
  workflow_call:
    inputs:
      java:
        type: string
        required: false
        default: 8
        description: TODO

jobs:
  cmd:
    name: JDK ${{ inputs.java }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.3

      - name: Install AdoptOpenJDK
        uses: coursier/setup-action@v1.1.2
        with:
          jvm: adopt:${{ inputs.java }}

      - name: Publish artifcats
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
