name: SBT command on matrix Java/Scala versions

on:
  workflow_call:
    inputs:
      java:
        type: string
        required: true
        description: TODO
      scala:
        type: string
        required: true
        description: TODO
      command:
        type: string
        required: true
        description: TODO

jobs:
  cmd:
    name: Scala ${{ matrix.scala }} & JDK ${{ matrix.jdk }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        jdk: ${{ inputs.java }}
        scala: ${{ inputs.scala }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.3

      - name: Install AdoptOpenJDK
        uses: coursier/setup-action@v1.1.2
        with:
          jvm: adopt:${{ inputs.java }}

      - name: Run sbt command
        run: ${{ inputs.command }}
        env:
          SCALA_VERSION: ${{ matrix.scala }}
